# Suhas Kesavan CSE22060

In [8]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_excel("C:/Users/Suhas K/Collage programs/SEM 5/Machine Learning/Lab Session Data.xlsx",sheet_name = None)
purchase_data = df['Purchase data'].iloc[:,:5]
purchase_data.head(10)
a = np.array(purchase_data[['Candies (#)','Mangoes (Kg)','Milk Packets (#)']])
c = np.array(purchase_data[['Payment (Rs)']])
print(a.shape)
print(c.shape)
print(a)
print(c)
rank_A = np.linalg.matrix_rank(a)
rank_A
ainv = np.linalg.pinv(a[:3][:3])
print(ainv)
c_1 = c[:3]
print(c_1)
x = np.dot(ainv,c[:3])
print("Final Ans = ",x)

(10, 3)
(10, 1)
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
[[-1.42857143e-01  6.43666939e-18  1.42857143e-01]
 [ 6.19047619e-01 -6.66666667e-02 -4.19047619e-01]
 [ 7.14285714e-02  2.00000000e-01 -1.71428571e-01]]
[[386]
 [289]
 [393]]
Final Ans =  [[ 1.]
 [55.]
 [18.]]


In [74]:
purchase_data['Status'] = ['RICH' if x>200 else "POOR" for x in purchase_data['Payment (Rs)']]
purchase_data

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Status
0      C_1           20             6                 2           386   RICH
1      C_2           16             3                 6           289   RICH
2      C_3           27             6                 2           393   RICH
3      C_4           19             1                 2           110   POOR
4      C_5           24             4                 2           280   RICH
5      C_6           22             1                 5           167   POOR
6      C_7           15             4                 2           271   RICH
7      C_8           18             4                 2           274   RICH
8      C_9           21             1                 4           148   POOR
9     C_10           16             2                 4           198   POOR

In [76]:
IRCTC_data = df['IRCTC Stock Price']
IRCTC_data

Date Month  Day    Price     Open     High      Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   
..            ...   ...  ...      ...      ...      ...      ...      ...   
244  Jul 07, 2020   Jul  Tue  1397.40  1410.00  1411.00  1390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1400.75  1405.50  1415.50  1394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1405.10  1415.00  1425.00  1398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1412.35  1440.00  1467.80  1395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1363.05  1363.65  1377.00  1356.00  383.00K   

       Chg%  
0    0.0020  
1    0.0043  
2   -0.0020  
3   -0.0026  
4   -0.0023  
..      ...  
244 -0.0024  
245 -0.0031  
246 -0.0051  
247  0.0362  
248  0.0032  

[249 rows x 9 columns]

In [86]:
import statistics as sts
price_m = sts.mean(IRCTC_data['Price'])
price_v = sts.variance(IRCTC_data['Price'])
print("Mean: ",price_m)
print("Variance: ",price_v)

Mean:  1560.663453815261
Variance:  58732.365352539186


In [91]:
price_wed = np.array([x if IRCTC_data['Day'] == 'Wed' for x in IRCTC_data['Price']])
price_wed

SyntaxError: expected 'else' after 'if' expression (1664695966.py, line 1)