# Suhas Kesavan CSE22060

In [8]:
import pandas as pd
import numpy as np

In [60]:
def find_x():
    df = pd.read_excel("C:/Users/Suhas K/Collage programs/SEM 5/Machine Learning/Lab Session Data.xlsx",sheet_name = None)
    purchase_data = df['Purchase data'].iloc[:,:5]
    purchase_data.head(10)
    a = np.array(purchase_data[['Candies (#)','Mangoes (Kg)','Milk Packets (#)']])
    c = np.array(purchase_data[['Payment (Rs)']])
    print(a.shape)
    print(c.shape)
    print(a)
    print(c)
    rank_A = np.linalg.matrix_rank(a)
    rank_A
    ainv = np.linalg.pinv(a[:3][:3])
    print(ainv)
    c_1 = c[:3]
    print(c_1)
    x = np.dot(ainv,c[:3])
    print("Final Ans = ",x)
find_x()

(10, 3)
(10, 1)
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
[[-1.42857143e-01  6.43666939e-18  1.42857143e-01]
 [ 6.19047619e-01 -6.66666667e-02 -4.19047619e-01]
 [ 7.14285714e-02  2.00000000e-01 -1.71428571e-01]]
[[386]
 [289]
 [393]]
Final Ans =  [[ 1.]
 [55.]
 [18.]]
