# Suhas Kesavan CSE22060

In [8]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_excel("C:/Users/Suhas K/Collage programs/SEM 5/Machine Learning/Lab Session Data.xlsx",sheet_name = None)
purchase_data = df['Purchase data'].iloc[:,:5]
purchase_data.head(10)
a = np.array(purchase_data[['Candies (#)','Mangoes (Kg)','Milk Packets (#)']])
c = np.array(purchase_data[['Payment (Rs)']])
print(a.shape)
print(c.shape)
print(a)
print(c)
rank_A = np.linalg.matrix_rank(a)
rank_A
ainv = np.linalg.pinv(a[:3][:3])
print(ainv)
c_1 = c[:3]
print(c_1)
x = np.dot(ainv,c[:3])
print("Final Ans = ",x)

(10, 3)
(10, 1)
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
[[-1.42857143e-01  6.43666939e-18  1.42857143e-01]
 [ 6.19047619e-01 -6.66666667e-02 -4.19047619e-01]
 [ 7.14285714e-02  2.00000000e-01 -1.71428571e-01]]
[[386]
 [289]
 [393]]
Final Ans =  [[ 1.]
 [55.]
 [18.]]


In [74]:
purchase_data['Status'] = ['RICH' if x>200 else "POOR" for x in purchase_data['Payment (Rs)']]
purchase_data

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Status
0      C_1           20             6                 2           386   RICH
1      C_2           16             3                 6           289   RICH
2      C_3           27             6                 2           393   RICH
3      C_4           19             1                 2           110   POOR
4      C_5           24             4                 2           280   RICH
5      C_6           22             1                 5           167   POOR
6      C_7           15             4                 2           271   RICH
7      C_8           18             4                 2           274   RICH
8      C_9           21             1                 4           148   POOR
9     C_10           16             2                 4           198   POOR